const categories = [
  {
    name: "Tâm Linh",
    slug: "tam-linh",
    parent: "Tâm Linh - Tôn Giáo",
    parentSlug: "tam-linh-ton-giao",
  },
  {
    name: "Thiền",
    slug: "thien",
    parent: "Tâm Linh - Tôn Giáo",
    parentSlug: "tam-linh-ton-giao",
  },
  {
    name: "Khoa Học Tự Nhiên",
    slug: "khoa-hoc-tu-nhien",
    parent: "Khoa học - Triết học",
    parentSlug: "khoa-hoc-triet-hoc-1",
  },
  {
    name: "Khoa Học Xã Hội",
    slug: "khoa-hoc-xa-hoi",
    parent: "Khoa học - Triết học",
    parentSlug: "khoa-hoc-triet-hoc-1",
  },
  {
    name: "Khoa Học Vũ Trụ",
    slug: "khoa-hoc-vu-tru",
    parent: "Khoa học - Triết học",
    parentSlug: "khoa-hoc-triet-hoc-1",
  },
  {
    name: "Triết Học Phương Tây",
    slug: "triet-hoc-phuong-tay",
    parent: "Khoa học - Triết học",
    parentSlug: "khoa-hoc-triet-hoc-1",
  },
  {
    name: "Minh Triết Phương Đông",
    slug: "minh-triet-phuong-dong",
    parent: "Khoa học - Triết học",
    parentSlug: "khoa-hoc-triet-hoc-1",
  },
  {
    name: "Địa Lý - Phong Thủy",
    slug: "dia-ly-phong-thuy",
    parent: "Khoa học - Triết học",
    parentSlug: "khoa-hoc-triet-hoc-1",
  },
  {
    name: "Quản Trị - Lãnh Đạo",
    slug: "quan-tri-lanh-dao",
    parent: "Kinh Tế - Chính Trị",
    parentSlug: "kinh-te-ky-nang",
  },
  {
    name: "Tài Chính - Kế Toán",
    slug: "tai-chinh-ke-toan-1",
    parent: "Kinh Tế - Chính Trị",
    parentSlug: "kinh-te-ky-nang",
  },
  {
    name: "Tiếp Thị - Bán Hàng",
    slug: "tiep-thi-ban-hang-1",
    parent: "Kinh Tế - Chính Trị",
    parentSlug: "kinh-te-ky-nang",
  },
  {
    name: "Kỹ Năng Làm Việc",
    slug: "ky-nang-lam-viec-1",
    parent: "Kinh Tế - Chính Trị",
    parentSlug: "kinh-te-ky-nang",
  },
  {
    name: "Thành Tựu Kinh Doanh",
    slug: "thanh-tuu-kinh-doanh-1",
    parent: "Kinh Tế - Chính Trị",
    parentSlug: "kinh-te-ky-nang",
  },
  {
    name: "Nghiên Cứu - Phân Tích",
    slug: "nghien-cuu-phan-tich-1",
    parent: "Kinh Tế - Chính Trị",
    parentSlug: "kinh-te-ky-nang",
  },
  {
    name: "Lịch Sử Việt Nam",
    slug: "lich-su-viet-nam",
    parent: "Lịch Sử",
    parentSlug: "lich-su-1",
  },
  {
    name: "Lịch Sử Thế Giới",
    slug: "lich-su-the-gioi",
    parent: "Lịch Sử",
    parentSlug: "lich-su-1",
  },
  {
    name: "Âm Nhạc",
    slug: "am-nhac-1",
    parent: "Văn Hóa - Nghệ Thuật",
    parentSlug: "van-hoa-nghe-thuat-1",
  },
  {
    name: "Hội Họa",
    slug: "hoi-hoa-1",
    parent: "Văn Hóa - Nghệ Thuật",
    parentSlug: "van-hoa-nghe-thuat-1",
  },
  {
    name: "Thi Ca",
    slug: "thi-ca-2",
    parent: "Văn Hóa - Nghệ Thuật",
    parentSlug: "van-hoa-nghe-thuat-1",
  },
  {
    name: "Mỹ Thuật - Kiến Trúc",
    slug: "my-thuat-kien-truc-1",
    parent: "Văn Hóa - Nghệ Thuật",
    parentSlug: "van-hoa-nghe-thuat-1",
  },
  {
    name: "Du Lịch",
    slug: "du-lich",
    parent: "Văn Hóa - Nghệ Thuật",
    parentSlug: "van-hoa-nghe-thuat-1",
  },
  {
    name: "Tiểu Thuyết Và Truyện Dài Việt Nam",
    slug: "tieu-thuyet-va-truyen-dai",
    parent: "Văn Học Việt Nam",
    parentSlug: "van-hoc/van-hoc-viet-nam",
  },
  {
    name: "Truyện Ngắn Việt Nam",
    slug: "truyen-ngan-2",
    parent: "Văn Học Việt Nam",
    parentSlug: "van-hoc/van-hoc-viet-nam",
    parent: "Văn Học Việt Nam",
    parentSlug: "van-hoc/van-hoc-viet-nam",
  },
  {
    name: "Tạp Văn Và Tản Văn Việt Nam",
    parent: "Văn Học Việt Nam",
    parentSlug: "van-hoc/van-hoc-viet-nam",
    slug: "tap-van-va-tan-van",
  },
  {
    name: "Khảo Cứu - Bút Ký",
    slug: "khao-cuu-va-but-ky",
    parent: "Văn Học Việt Nam",
    parentSlug: "van-hoc/van-hoc-viet-nam",
  },
  {
    name: "Tiểu Thuyết Và Truyện Dài Thế Giới",
    slug: "tieu-thuyet-va-truyen-dai-1",
    parent: "Văn Học Thế Giới",
    parentSlug: "van-hoc/van-hoc-the-gioi",
  },
  {
    name: "Truyện Ngắn Thế Giới",
    slug: "truyen-ngan-1",
    parent: "Văn Học Thế Giới",
    parentSlug: "van-hoc/van-hoc-the-gioi",
  },
  {
    name: "Khảo Cứu - Bút Ký Thế Giới",
    slug: "khao-cuu-va-but-ky-1",
    parent: "Văn Học Thế Giới",
    parentSlug: "van-hoc/van-hoc-the-gioi",
  },
  {
    name: "Tâm Lý",
    slug: "tam-ly",
    parent: "Tâm Lý - Nghệ Thuật Sống",
    parentSlug: "tam-ly-nghe-thuat-song",
  },
  {
    name: "Định Hướng Sống",
    slug: "dinh-huong-song",
    parent: "Tâm Lý - Nghệ Thuật Sống",
    parentSlug: "tam-ly-nghe-thuat-song",
  },
  {
    name: "Kỹ Năng Sống",
    slug: "ky-nang-song",
    parent: "Tâm Lý - Nghệ Thuật Sống",
    parentSlug: "tam-ly-nghe-thuat-song",
  },
  {
    name: "Câu Chuyện Sống",
    slug: "nghe-thuat-song/cau-chuyen-song",
    parent: "Tâm Lý - Nghệ Thuật Sống",
    parentSlug: "tam-ly-nghe-thuat-song",
  },
  {
    name: "Gương Vĩ Đại",
    slug: "guong-vi-dai",
    parent: "Nghệ Thuật Sống",
    parentSlug: "tam-ly-nghe-thuat-song",
  },
  {
    name: "Dưỡng Sinh - Yoga",
    slug: "dung-sinh-yoga",
    parent: "Y Học - Thực Dưỡng",
    parentSlug: "y-hoc-thuc-dung-1",
  },
  {
    name: "Ẩm Thực",
    slug: "am-thuc",
    parent: "Y Học - Thực Dưỡng",
    parentSlug: "y-hoc-thuc-dung-1",
  },
  {
    name: "Giáo Dục",
    slug: "giao-duc",
    parent: "Giaó Dục - Gia Đình",
    parentSlug: "sach-gia-dinh",
  },
  {
    name: "Thiếu Nhi",
    slug: "thieu-nhi",
    parent: "Giaó Dục - Gia Đình",
    parentSlug: "sach-gia-dinh",
  },
  {
    name: "Thiếu Niên",
    slug: "thieu-nien",
    parent: "Giaó Dục - Gia Đình",
    parentSlug: "sach-gia-dinh",
  },
  {
    name: "Làm Cha Mẹ",
    slug: "lam-cha-me",
    parent: "Giaó Dục - Gia Đình",
    parentSlug: "sach-gia-dinh",
  },
  {
    name: "Nghiệp Vụ",
    slug: "nghiep-vu",
    parent: "Kỹ Năng Thường Thức",
    parentSlug: "ky-nang-thuong-thuc",
  },
  {
    name: "Từ Điễn",
    slug: "tu-dien",
    parent: "Kỹ Năng Thường Thức",
    parentSlug: "ky-nang-thuong-thuc",
  },
  {
    name: "Ngoại Ngữ",
    slug: "ngoai-ngu",
    parent: "Kỹ Năng Thường Thức",
    parentSlug: "ky-nang-thuong-thuc",
  },
];

module.exports = categories;
